type UserInfo @aws_iam @aws_cognito_user_pools {
  username: String!
  firstName: String!
  lastName: String
  bio: String
  profilePhoto: String
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  owner: String
}

type Projects @aws_iam @aws_cognito_user_pools {
  title: String!
  description: String!
  templateId: ID
  template: Templates
  author: String
  icon: AWSURL
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}

type Templates @aws_iam @aws_cognito_user_pools {
  title: String!
  description: String!
  templateId: ID
  projects(filter: ModelProjectsFilterInput, sortDirection: ModelSortDirection, limit: Int, nextToken: String): ModelProjectsConnection
  author: String
  icon: AWSURL
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}

input AmplifyAIConversationTurnErrorInput {
  errorType: String!
  message: String!
}

input ModelStringInput {
  ne: String
  eq: String
  le: String
  lt: String
  ge: String
  gt: String
  contains: String
  notContains: String
  between: [String]
  beginsWith: String
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
  size: ModelSizeInput
}

input ModelIntInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelFloatInput {
  ne: Float
  eq: Float
  le: Float
  lt: Float
  ge: Float
  gt: Float
  between: [Float]
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelBooleanInput {
  ne: Boolean
  eq: Boolean
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelIDInput {
  ne: ID
  eq: ID
  le: ID
  lt: ID
  ge: ID
  gt: ID
  contains: ID
  notContains: ID
  between: [ID]
  beginsWith: ID
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
  size: ModelSizeInput
}

input ModelSubscriptionStringInput {
  ne: String
  eq: String
  le: String
  lt: String
  ge: String
  gt: String
  contains: String
  notContains: String
  between: [String]
  beginsWith: String
  in: [String]
  notIn: [String]
}

input ModelSubscriptionIntInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
  in: [Int]
  notIn: [Int]
}

input ModelSubscriptionFloatInput {
  ne: Float
  eq: Float
  le: Float
  lt: Float
  ge: Float
  gt: Float
  between: [Float]
  in: [Float]
  notIn: [Float]
}

input ModelSubscriptionBooleanInput {
  ne: Boolean
  eq: Boolean
}

input ModelSubscriptionIDInput {
  ne: ID
  eq: ID
  le: ID
  lt: ID
  ge: ID
  gt: ID
  contains: ID
  notContains: ID
  between: [ID]
  beginsWith: ID
  in: [ID]
  notIn: [ID]
}

enum ModelAttributeTypes {
  binary
  binarySet
  bool
  list
  map
  number
  numberSet
  string
  stringSet
  _null
}

input ModelSizeInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
}

enum ModelSortDirection {
  ASC
  DESC
}

type ModelUserInfoConnection @aws_iam @aws_cognito_user_pools {
  items: [UserInfo]!
  nextToken: String
}

input ModelUserInfoFilterInput {
  username: ModelStringInput
  firstName: ModelStringInput
  lastName: ModelStringInput
  bio: ModelStringInput
  profilePhoto: ModelStringInput
  id: ModelIDInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  and: [ModelUserInfoFilterInput]
  or: [ModelUserInfoFilterInput]
  not: ModelUserInfoFilterInput
  owner: ModelStringInput
}

type Query {
  getUserInfo(id: ID!): UserInfo @aws_iam @aws_cognito_user_pools
  listUserInfos(filter: ModelUserInfoFilterInput, limit: Int, nextToken: String): ModelUserInfoConnection @aws_iam @aws_cognito_user_pools
  getProjects(id: ID!): Projects @aws_iam @aws_cognito_user_pools
  listProjects(filter: ModelProjectsFilterInput, limit: Int, nextToken: String): ModelProjectsConnection @aws_iam @aws_cognito_user_pools
  getTemplates(id: ID!): Templates @aws_iam @aws_cognito_user_pools
  listTemplates(filter: ModelTemplatesFilterInput, limit: Int, nextToken: String): ModelTemplatesConnection @aws_iam @aws_cognito_user_pools
}

input ModelUserInfoConditionInput {
  username: ModelStringInput
  firstName: ModelStringInput
  lastName: ModelStringInput
  bio: ModelStringInput
  profilePhoto: ModelStringInput
  and: [ModelUserInfoConditionInput]
  or: [ModelUserInfoConditionInput]
  not: ModelUserInfoConditionInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  owner: ModelStringInput
}

input CreateUserInfoInput {
  username: String!
  firstName: String!
  lastName: String
  bio: String
  profilePhoto: String
  id: ID
}

input UpdateUserInfoInput {
  username: String
  firstName: String
  lastName: String
  bio: String
  profilePhoto: String
  id: ID!
}

input DeleteUserInfoInput {
  id: ID!
}

type Mutation {
  createUserInfo(input: CreateUserInfoInput!, condition: ModelUserInfoConditionInput): UserInfo @aws_iam @aws_cognito_user_pools
  updateUserInfo(input: UpdateUserInfoInput!, condition: ModelUserInfoConditionInput): UserInfo @aws_iam @aws_cognito_user_pools
  deleteUserInfo(input: DeleteUserInfoInput!, condition: ModelUserInfoConditionInput): UserInfo @aws_iam @aws_cognito_user_pools
  createProjects(input: CreateProjectsInput!, condition: ModelProjectsConditionInput): Projects @aws_iam @aws_cognito_user_pools
  updateProjects(input: UpdateProjectsInput!, condition: ModelProjectsConditionInput): Projects @aws_iam @aws_cognito_user_pools
  deleteProjects(input: DeleteProjectsInput!, condition: ModelProjectsConditionInput): Projects @aws_iam @aws_cognito_user_pools
  createTemplates(input: CreateTemplatesInput!, condition: ModelTemplatesConditionInput): Templates @aws_iam @aws_cognito_user_pools
  updateTemplates(input: UpdateTemplatesInput!, condition: ModelTemplatesConditionInput): Templates @aws_iam @aws_cognito_user_pools
  deleteTemplates(input: DeleteTemplatesInput!, condition: ModelTemplatesConditionInput): Templates @aws_iam @aws_cognito_user_pools
}

input ModelSubscriptionUserInfoFilterInput {
  username: ModelSubscriptionStringInput
  firstName: ModelSubscriptionStringInput
  lastName: ModelSubscriptionStringInput
  bio: ModelSubscriptionStringInput
  profilePhoto: ModelSubscriptionStringInput
  id: ModelSubscriptionIDInput
  createdAt: ModelSubscriptionStringInput
  updatedAt: ModelSubscriptionStringInput
  and: [ModelSubscriptionUserInfoFilterInput]
  or: [ModelSubscriptionUserInfoFilterInput]
  owner: ModelStringInput
}

type Subscription {
  onCreateUserInfo(filter: ModelSubscriptionUserInfoFilterInput, owner: String): UserInfo @aws_subscribe(mutations: ["createUserInfo"]) @aws_iam @aws_cognito_user_pools
  onUpdateUserInfo(filter: ModelSubscriptionUserInfoFilterInput, owner: String): UserInfo @aws_subscribe(mutations: ["updateUserInfo"]) @aws_iam @aws_cognito_user_pools
  onDeleteUserInfo(filter: ModelSubscriptionUserInfoFilterInput, owner: String): UserInfo @aws_subscribe(mutations: ["deleteUserInfo"]) @aws_iam @aws_cognito_user_pools
  onCreateProjects(filter: ModelSubscriptionProjectsFilterInput, author: String): Projects @aws_subscribe(mutations: ["createProjects"]) @aws_iam @aws_cognito_user_pools
  onUpdateProjects(filter: ModelSubscriptionProjectsFilterInput, author: String): Projects @aws_subscribe(mutations: ["updateProjects"]) @aws_iam @aws_cognito_user_pools
  onDeleteProjects(filter: ModelSubscriptionProjectsFilterInput, author: String): Projects @aws_subscribe(mutations: ["deleteProjects"]) @aws_iam @aws_cognito_user_pools
  onCreateTemplates(filter: ModelSubscriptionTemplatesFilterInput, author: String): Templates @aws_subscribe(mutations: ["createTemplates"]) @aws_iam @aws_cognito_user_pools
  onUpdateTemplates(filter: ModelSubscriptionTemplatesFilterInput, author: String): Templates @aws_subscribe(mutations: ["updateTemplates"]) @aws_iam @aws_cognito_user_pools
  onDeleteTemplates(filter: ModelSubscriptionTemplatesFilterInput, author: String): Templates @aws_subscribe(mutations: ["deleteTemplates"]) @aws_iam @aws_cognito_user_pools
}

type ModelProjectsConnection @aws_iam @aws_cognito_user_pools {
  items: [Projects]!
  nextToken: String
}

input ModelProjectsFilterInput {
  title: ModelStringInput
  description: ModelStringInput
  templateId: ModelIDInput
  author: ModelStringInput
  icon: ModelStringInput
  id: ModelIDInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  and: [ModelProjectsFilterInput]
  or: [ModelProjectsFilterInput]
  not: ModelProjectsFilterInput
}

input ModelProjectsConditionInput {
  title: ModelStringInput
  description: ModelStringInput
  templateId: ModelIDInput
  author: ModelStringInput
  icon: ModelStringInput
  and: [ModelProjectsConditionInput]
  or: [ModelProjectsConditionInput]
  not: ModelProjectsConditionInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
}

input CreateProjectsInput {
  title: String!
  description: String!
  templateId: ID
  author: String
  icon: AWSURL
  id: ID
}

input UpdateProjectsInput {
  title: String
  description: String
  templateId: ID
  author: String
  icon: AWSURL
  id: ID!
}

input DeleteProjectsInput {
  id: ID!
}

input ModelSubscriptionProjectsFilterInput {
  title: ModelSubscriptionStringInput
  description: ModelSubscriptionStringInput
  templateId: ModelSubscriptionIDInput
  icon: ModelSubscriptionStringInput
  id: ModelSubscriptionIDInput
  createdAt: ModelSubscriptionStringInput
  updatedAt: ModelSubscriptionStringInput
  and: [ModelSubscriptionProjectsFilterInput]
  or: [ModelSubscriptionProjectsFilterInput]
  author: ModelStringInput
}

type ModelTemplatesConnection @aws_iam @aws_cognito_user_pools {
  items: [Templates]!
  nextToken: String
}

input ModelTemplatesFilterInput {
  title: ModelStringInput
  description: ModelStringInput
  templateId: ModelIDInput
  author: ModelStringInput
  icon: ModelStringInput
  id: ModelIDInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  and: [ModelTemplatesFilterInput]
  or: [ModelTemplatesFilterInput]
  not: ModelTemplatesFilterInput
}

input ModelTemplatesConditionInput {
  title: ModelStringInput
  description: ModelStringInput
  templateId: ModelIDInput
  author: ModelStringInput
  icon: ModelStringInput
  and: [ModelTemplatesConditionInput]
  or: [ModelTemplatesConditionInput]
  not: ModelTemplatesConditionInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
}

input CreateTemplatesInput {
  title: String!
  description: String!
  templateId: ID
  author: String
  icon: AWSURL
  id: ID
}

input UpdateTemplatesInput {
  title: String
  description: String
  templateId: ID
  author: String
  icon: AWSURL
  id: ID!
}

input DeleteTemplatesInput {
  id: ID!
}

input ModelSubscriptionTemplatesFilterInput {
  title: ModelSubscriptionStringInput
  description: ModelSubscriptionStringInput
  templateId: ModelSubscriptionIDInput
  icon: ModelSubscriptionStringInput
  id: ModelSubscriptionIDInput
  createdAt: ModelSubscriptionStringInput
  updatedAt: ModelSubscriptionStringInput
  and: [ModelSubscriptionTemplatesFilterInput]
  or: [ModelSubscriptionTemplatesFilterInput]
  author: ModelStringInput
}
