import { Inter, JetBrains_Mono } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar/navbar'

// FontAwesome Config
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter',
})

const jetbrains_mono = JetBrains_Mono({ 
  subsets: ['latin'],
  variable: '--font-jetbrains-mono',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {  
  return (
    <>
      <html lang="en" className=' overflow-hidden'>
        <body className={` h-screen bg-[var(--light-bg-3)] dark:bg-[var(--dark-bg-3)] ${inter.variable} ${jetbrains_mono.variable}`}>
          <Navbar />
          {children}
        </body>
      </html>
    </>
  )
}
